# Generated by Django 3.0.5 on 2020-10-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Message', models.CharField(max_length=1000)),
                ('Created', models.DateField()),
                ('Updated', models.DateField()),
            ],
        ),
    ]
