# Generated by Django 3.0.5 on 2020-10-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COURSE_TABLE',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Course_Name', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Message', models.CharField(max_length=1000)),
                ('Created', models.DateField()),
                ('Updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HOD_ADMIN',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LEAVE_TABLE',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Leave_Date', models.DateField()),
                ('Created', models.DateField()),
                ('Updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('password', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('password', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('course_id', models.IntegerField()),
            ],
        ),
    ]
