# Generated by Django 3.0.5 on 2020-10-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Attendance_ID', models.IntegerField()),
                ('Status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification_Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1000)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SUBJECT_TABLE',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Subject_Name', models.CharField(max_length=100)),
                ('Course_ID', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
        ),
    ]
